### ISSUE TITLE
Admin Sorting Depends on Activation Hack

### ISSUE THREAD

**Issue by robneu** [wpsitecare/admin-content-labels#1]
In order for the admin columns to be sorted correctly, some reference to the custom meta field needs to be made. Right now, the only way I've been able to get this working is by using the post title as a fallback for the admin label when none is set. Doing this allows us to sort by the meta_value rather than the post_title and get the correct sort.

The major issue with this is that in order for it to work, we need to update all existing content on plugin activation so that the meta value is always set. Right now this is done by looping through all existing content and using add_post_meta. On smaller sites, this should work fine; however, on larger sites it could be a problem. I'd like to either get away from this sorting method or figure out a better way to process the existing content on plugin activation.

**Comment by shawnhooper** [comment]
I think I have a solution that will be more reliable on large installs than the current method.  Will try it out and submit a PR tonight.

**Comment by robneu** [comment]
Thank you sir! Any help is much appreciated.
